import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowDown, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLanguage } from '@/components/veldr/language';
import { Reveal, useHeroMotion } from '@/components/veldr/motion';
import { pageMeta } from '@/components/veldr/page-meta';
import { copy, views } from '@/lib/veldr-content';
export const Route = createFileRoute('/')({ head: () => pageMeta('VELDR O/01 — The Long Way', 'A fictional 4×4 design concept. Discover the upright exterior, considered cabin and three-view VELDR O/01 showroom.'), component: Home });
function Home() {
  const { t } = useLanguage();
  const hero = useHeroMotion();
  return <>
    <section ref={hero} className="hero" aria-labelledby="hero-title">
      <div className="hero-image" role="img" aria-label={t(views[0].alt)}/><div className="hero-scrim" aria-hidden="true"/>
      <div className="hero-inner wrap"><div className="hero-copy"><p className="eyebrow hero-eyebrow"><span className="eyebrow-line"/>O/01 <span className="eyebrow-separator">/</span>{t(copy('4×4 CONCEPT', '四驱概念车'))}</p><h1 id="hero-title">THE<br/>LONG<br/><span>WAY.</span></h1><p className="hero-description">{t(copy('The road changes. The reason to go doesn’t.', '路况会变，出发的念头不变。'))}</p><div className="hero-actions"><Button variant="showroom" asChild><Link to="/explore">{t(copy('Explore O/01', '探索车型'))}<ArrowUpRight/></Link></Button><Link className="text-link" to="/design">{t(copy('Discover the design', '了解设计'))}<ArrowDown size={16}/></Link></div></div><div className="hero-foot"><span>01 / 04</span><a className="hero-scroll" href="#idea"><span/>{t(copy('SCROLL TO EXPLORE', '向下探索'))}</a><span>{t(copy('BUILT FOR THE DETOUR', '为远行而构想'))}</span></div></div>
    </section>
    <section id="idea" className="intro section-pad"><div className="wrap editorial-grid"><Reveal><div className="section-index"><span>01</span>{t(copy('THE IDEA', '设计起点'))}</div></Reveal><Reveal><p className="eyebrow">{t(copy('MEET O/01', '认识 O/01'))}</p><h2 className="display-heading">{t(copy('Not every road', '不是每一段路'))}<br/><span>{t(copy('is on the map.', '都画在地图上。'))}</span></h2><div className="intro-bottom"><p>{t(copy('O/01 starts with an upright body and a clear silhouette. Open glazing considers the view; a square rear imagines room for luggage and equipment. Between everyday life and a longer journey, there is no need to rush the choice.', 'O/01 从直立车身和清晰轮廓出发。开阔车窗照顾视野，方正车尾留给行李与装备。日常与远行之间，不必急着做取舍。'))}</p><Link className="arrow-link" to="/design">{t(copy('Study the exterior', '查看车身设计'))}<ArrowUpRight/></Link></div></Reveal></div></section>
    <section className="profile"><Reveal className="profile-image-wrap"><img src={views[1].image} alt={t(views[1].alt)} loading="lazy"/><span className="image-caption">{t(copy('FORM STUDY / PROFILE 01', '造型研究 / 侧面 01'))}</span></Reveal><div className="wrap editorial-grid section-pad"><Reveal><div className="section-index"><span>02</span>{t(copy('THE FORM', '车身轮廓'))}</div></Reveal><Reveal><p className="eyebrow">{t(copy('THE O/01 SILHOUETTE', 'O/01 的轮廓'))}</p><h2 className="display-heading">{t(copy('Square in shape.', '车身方正，'))}<br/><span>{t(copy('Direct in intent.', '想法很直接。'))}</span></h2><p className="body-copy">{t(copy('A straight roof. Upright windows. Wheel arches that reach outward. O/01 builds its silhouette from clear geometry, with little decoration.', '平直的车顶，直立的车窗，向外展开的轮拱。O/01 用清楚的几何关系建立轮廓，装饰留得很少。'))}</p><Link className="arrow-link" to="/design">{t(copy('Explore the proportions', '探索车身比例'))}<ArrowUpRight/></Link></Reveal></div></section>
    <section className="details-section section-pad"><div className="wrap"><div className="section-index"><span>03</span>{t(copy('THE DETAILS', '使用细节'))}</div><Reveal className="details-heading"><p className="eyebrow">{t(copy('VISIBILITY / SPACE / CONTROL', '视野 / 空间 / 操作'))}</p><h2 className="display-heading">{t(copy('Look ahead.', '看清前方。'))}<br/><span>{t(copy('Bring what matters.', '带上想带的。'))}</span></h2></Reveal><div className="principles">{[
      { n: '01 / VISIBILITY', title: copy('An open outlook', '视线更开阔'), text: copy('An upright seating position and broad side windows put the road and changing landscape at the centre of the design.', '高坐姿与开阔侧窗，将道路与变化的风景放在设计的中心。') },
      { n: '02 / UTILITY', title: copy('Room for the journey', '多带一点'), text: copy('A level roof and a square rear express the intention to make room for luggage, camera cases and the gear added at the last minute.', '平直车顶与方正车尾，表达为行李、摄影箱和临时加上的装备留出空间的设想。') },
      { n: '03 / CONTROL', title: copy('A direct touch', '伸手就能用'), text: copy('In this cabin study, frequent adjustments belong to physical knobs, not a succession of screen menus.', '在这份座舱设想里，常用操作交给实体旋钮，不必层层翻找屏幕。') },
    ].map((item) => <Reveal key={item.n} className="principle"><span className="eyebrow">{t(copy(item.n, item.n.startsWith('01') ? '01 / 视野' : item.n.startsWith('02') ? '02 / 空间' : '03 / 操作'))}</span><h3>{t(item.title)}</h3><p>{t(item.text)}</p></Reveal>)}</div></div></section>
    <section className="cabin-preview"><Reveal className="cabin-preview-image"><img src={views[2].image} alt={t(views[2].alt)} loading="lazy"/></Reveal><div className="wrap editorial-grid section-pad"><div className="section-index"><span>04</span>{t(copy('THE CABIN', '座舱空间'))}</div><Reveal><p className="eyebrow">{t(copy('INSIDE O/01', 'O/01 的座舱'))}</p><h2 className="display-heading">{t(copy('The road is long.', '路很长。'))}<br/><span>{t(copy('Keep the cabin simple.', '座舱不必复杂。'))}</span></h2><p className="body-copy">{t(copy('A dark dashboard quiets the view. Warm brown seats keep a little warmth. Physical knobs are close at hand, with everyday controls clearly arranged.', '深色仪表台让视线安静下来，暖棕座椅留下一点温度。实体旋钮在手边，常用操作一目了然。'))}</p><Link className="arrow-link" to="/cabin">{t(copy('Step inside', '走进座舱'))}<ArrowUpRight/></Link></Reveal></div></section>
    <section className="closing section-pad"><div className="wrap"><Reveal><p className="eyebrow">VELDR / O/01</p><h2 className="closing-title">{t(copy('The next road.', '下一段路，'))}<br/><span>{t(copy('Your direction.', '自己决定。'))}</span></h2><p>{t(copy('Three views. One idea. See the exterior and cabin together, and take a closer look at the design.', '三个视角，同一个想法。将车身与座舱放在一起，细看这份设计。'))}</p><Button variant="showroom" asChild><Link to="/explore">{t(copy('Enter the showroom', '进入展厅'))}<ArrowUpRight/></Link></Button></Reveal></div></section>
  </>;
}
