import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowDown, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useLanguage } from '@/components/veldr/language';
import { useHeroMotion } from '@/components/veldr/motion';
import { pageMeta } from '@/components/veldr/page-meta';
import { copy, views } from '@/lib/veldr-content';
import { StudyImage, RoadInterlude } from '@/components/veldr/art-studies';
export const Route = createFileRoute('/')({ head: () => pageMeta('VELDR O/01 — The Long Way', 'A fictional 4×4 design concept. Discover the upright exterior, considered cabin and three-view VELDR O/01 showroom.'), component: Home });
function Home() {
  const { t } = useLanguage();
  const hero = useHeroMotion();
  return <>
    <section ref={hero} className="hero" aria-labelledby="hero-title">
      <div className="hero-image" role="img" aria-label={t(views[0].alt)}/><div className="hero-scrim" aria-hidden="true"/>
      <div className="hero-inner wrap"><div className="hero-copy"><p className="eyebrow hero-eyebrow"><span className="eyebrow-line"/>O/01 <span className="eyebrow-separator">/</span>{t(copy('4×4 CONCEPT', '四驱概念车'))}</p><h1 id="hero-title">THE<br/>LONG<br/><span>WAY.</span></h1><p className="hero-description">{t(copy('The road changes. The reason to go doesn’t.', '路况会变，出发的念头不变。'))}</p><div className="hero-actions"><Button variant="showroom" asChild><Link to="/explore">{t(copy('Explore O/01', '探索车型'))}<ArrowUpRight/></Link></Button><Link className="text-link" to="/design">{t(copy('Discover the design', '了解设计'))}<ArrowDown size={16}/></Link></div></div><div className="hero-foot"><span>01 / 04</span><a className="hero-scroll" href="#idea"><span/>{t(copy('SCROLL TO EXPLORE', '向下探索'))}</a><span>{t(copy('BUILT FOR THE DETOUR', '为远行而构想'))}</span></div></div>
    </section>
    <section id="idea" className="journey-opening"><div className="wrap journey-layout"><div><p className="eyebrow">{t(copy('MEET O/01', '认识 O/01'))}</p><h2>{t(copy('Not every road', '不是每一段路'))}<br/><span>{t(copy('is on the map.', '都画在地图上。'))}</span></h2><p>{t(copy('O/01 starts with an upright body and a clear silhouette. Open glazing considers the view; a square rear imagines room for luggage and equipment. Between everyday life and a longer journey, there is no need to rush the choice.', 'O/01 从直立车身和清晰轮廓出发。开阔车窗照顾视野，方正车尾留给行李与装备。日常与远行之间，不必急着做取舍。'))}</p><Link className="arrow-link" to="/design">{t(copy('Study the exterior', '查看车身设计'))}<ArrowUpRight/></Link></div><figure><StudyImage study="equipment"/><figcaption>{t(copy('JOURNEY OBJECTS / A STILL-LIFE STUDY', '旅途物件 / 静物研究'))}</figcaption></figure></div></section>
    <section className="profile-study"><div className="wrap"><header><p className="eyebrow">{t(copy('THE O/01 SILHOUETTE', 'O/01 的轮廓'))}</p><h2>{t(copy('Square in shape. Direct in intent.', '车身方正，想法很直接。'))}</h2></header><figure><img src={views[1].image} width="1672" height="941" alt={t(views[1].alt)} loading="lazy"/><figcaption><span>{t(copy('FORM STUDY / COMPLETE SIDE PROFILE', '造型研究 / 完整侧面'))}</span><Link className="arrow-link" to="/design">{t(copy('Explore the proportions', '探索车身比例'))}<ArrowUpRight/></Link></figcaption></figure><p className="profile-note">{t(copy('A straight roof. Upright windows. Wheel arches that reach outward. O/01 builds its silhouette from clear geometry, with little decoration.', '平直的车顶，直立的车窗，向外展开的轮拱。O/01 用清楚的几何关系建立轮廓，装饰留得很少。'))}</p></div></section>
    <RoadInterlude/>
    <section className="field-notes"><div className="wrap"><header><p className="eyebrow">{t(copy('VISIBILITY / SPACE / CONTROL', '视野 / 空间 / 操作'))}</p><h2>{t(copy('Look ahead. Bring what matters.', '看清前方。带上想带的。'))}</h2></header><div className="field-layout"><figure className="field-material"><StudyImage study="material"/><figcaption>{t(copy('COLOUR & MATERIAL / A CONCEPT STUDY', '色彩与材质 / 概念研究'))}</figcaption></figure><article className="field-utility"><h3>{t(copy('Room for the journey', '多带一点'))}</h3><p>{t(copy('A level roof and a square rear express the intention to make room for luggage, camera cases and the gear added at the last minute.', '平直车顶与方正车尾，表达为行李、摄影箱和临时加上的装备留出空间的设想。'))}</p><StudyImage study="equipment"/></article><article className="field-control"><StudyImage study="controls"/><h3>{t(copy('A direct touch', '伸手就能用'))}</h3><p>{t(copy('In this cabin study, frequent adjustments belong to physical knobs, not a succession of screen menus.', '在这份座舱设想里，常用操作交给实体旋钮，不必层层翻找屏幕。'))}</p></article><article className="field-outlook"><h3>{t(copy('An open outlook', '视线更开阔'))}</h3><p>{t(copy('An upright seating position and broad side windows put the road and changing landscape at the centre of the design.', '高坐姿与开阔侧窗，将道路与变化的风景放在设计的中心。'))}</p></article></div></div></section>
    <section className="cabin-spread"><div className="wrap"><header><p className="eyebrow">{t(copy('INSIDE O/01', 'O/01 的座舱'))}</p><h2>{t(copy('The road is long. Keep the cabin simple.', '路很长。座舱不必复杂。'))}</h2></header><figure className="cabin-main"><img src={views[2].image} width="1672" height="941" alt={t(views[2].alt)} loading="lazy"/><figcaption>{t(copy('CABIN STUDY / ORIGINAL CONCEPT VIEW', '座舱研究 / 原始概念视图'))}</figcaption></figure><div className="cabin-after"><figure><StudyImage study="material"/><figcaption>{t(copy('MATERIAL STUDY / NOT A PRODUCTION SPECIFICATION', '材质研究 / 非量产配置'))}</figcaption></figure><div><p>{t(copy('A dark dashboard quiets the view. Warm brown seats keep a little warmth. Physical knobs are close at hand, with everyday controls clearly arranged.', '深色仪表台让视线安静下来，暖棕座椅留下一点温度。实体旋钮在手边，常用操作一目了然。'))}</p><Link className="arrow-link" to="/cabin">{t(copy('Step inside', '走进座舱'))}<ArrowUpRight/></Link></div></div></div></section>
    <section className="showroom-ending"><div className="wrap"><div><p className="eyebrow">VELDR / O/01</p><h2>{t(copy('Three views. One idea.', '三个视角，同一个想法。'))}</h2><p>{t(copy('See the exterior and cabin together, and take a closer look at the design.', '将车身与座舱放在一起，细看这份设计。'))}</p></div><Button variant="showroom" asChild><Link to="/explore">{t(copy('Enter the showroom', '进入展厅'))}<ArrowUpRight/></Link></Button></div></section>
  </>;
}
